apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-feed
  labels:
    app: backend-feed
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend-feed
  template:
    metadata:
      labels:
        app: backend-feed
    spec:
      containers:
      - name: backend-feed
        image: honorezemagho/udagram-api-feed:v1
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "256Mi"
              cpu: "400m"
        ports:
        - containerPort: 8080
        envFrom:
          - configMapRef:
              name: env-udagram-configmap
          - secretRef:
              name: env-udagram-pg
        volumeMounts:
          - mountPath: "/root/.aws"
            name: udagram-aws-creds
      volumes: 
        - name: udagram-aws-creds
          configMap: 
            name: udagram-aws-creds